name: Item API Deploy and E2E Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 19 * * *'  # 7:30 am NZT (UTC+12)

jobs:
  test:
    runs-on: ubuntu-latest

#    services:
#      api:
#        image: node:18
#        ports:
#          - 3333:3333
#        env:
#          CI: true
#        options: >-
#          --health-cmd="curl --fail http://localhost:3333/api-docs || exit 1"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=15
#        volumes:
#          - .:/app
#        command: sh -c "cd /app && npm ci && node server.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Install dependencies
#        run: npm ci

      - name: Install app dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

#      - name: Start API in background
#        run: node server.js

      - name: Wait for API service to be healthy
        run: |
          for i in {1..20}; do
            if nc -z localhost 3333; then
              echo "Item API is up!";
              break;
            fi;
            echo "Waiting for the API to be ready...";
            sleep 3;
          done

      - name: Install Cypress
        run: npm install --save-dev cypress

#      - name: Run Cypress tests in Docker
#        env:
#          CYPRESS_baseUrl: http://localhost:3333
#        run: npx cypress run

      - name: Run Cypress tests in Docker
        run: |
          docker run --rm \
           -v ${{ github.workspace }}:/e2e \
           -w /e2e \
           -e CYPRESS_baseUrl=http://localhost:3333 \
           --entrypoint /bin/sh \
           cypress/included:13.3.2 \
           -c "npm install && npx cypress run"  

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/reports/result.html
            cypress/videos
            cypress/screenshots
