name: Item API Deploy and E2E Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 19 * * *'  # 7:30 am NZT (UTC+12)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-13.15.0
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install app dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Run unit tests
        run: |
          nohup npm test &
          npx wait-on http://localhost:3333/api-docs --timeout 5000

      - name: Start API
        run: |
          nohup node server.js &
          npx wait-on http://localhost:3333/api-docs --timeout 30000

      - name: Run Cypress tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            -e CYPRESS_baseUrl=http://localhost:3333 \
            --network host \
            cypress/included:13.15.0 \
            npx cypress run

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/reports/result.html
            cypress/videos
            cypress/screenshots

      - name: Cleanup
        if: always()
        run: pkill node || true
